# services:
#   backend:
#     build: ./server
#     container_name: texmarket_backend
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./server:/app
#       - /app/node_modules
#     environment:
#       - CLIENT_URL=http://localhost:5173
#       - NODE_ENV=development
#     env_file:
#       - ./server/.env

#   frontend:
#     build: ./client
#     container_name: texmarket_frontend
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./client:/app
#       - /app/node_modules
#     environment:
#       - VITE_API_URL=http://localhost:5000



services:
  redis:
    image: redis:alpine
    container_name: texmarket_redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./server
    container_name: texmarket_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      CLIENT_URL: http://localhost:5173
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: ""
      REDIS_PASSWORD: ""
    env_file:
      - ./server/.env
    depends_on:
      - redis
    command: npm run dev

  frontend:
    build:
      context: ./client
    container_name: texmarket_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000
    command: npm run dev -- --host 0.0.0.0