services:
  backend:
    build: ./server
    container_name: texmarket_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - CLIENT_URL=http://localhost:5173
      - NODE_ENV=development
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: texmarket_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
